[package]
name = "racing_game"
version = "0.1.0"
authors = ["mertwole <mertwole@gmail.com>"]
edition = "2018"

[dependencies]
glfw = "*"
gl = "*"
image = "*"
rand = "*"
include_dir = "*"
readonly = "*"